# -*- coding: utf-8 -*-
"""Diabetes_backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_PjLXfCjzJ-DBi5XiKK9YnyeLPaFo7q
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import pickle

diabetes=pd.read_excel("/content/logisticdiabetes(1).xlsx")

diabetes.head()

diabetes.info()

diabetes.isnull().sum()

a=diabetes[['plas','pres','insu','mass']]

b=diabetes['class']

logr=LogisticRegression()

logr.fit(a,b)

with open('diabetes_model.pkl', 'wb') as f:
    pickle.dump(logr,f)
print("Model trained and saved as'diabetes_model.pkl'")